// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkbmjgxiulgmcmiphtql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rYm1qZ3hpdWxnbWNtaXBodHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTYzMDUsImV4cCI6MjA2NDc3MjMwNX0.yn17VZFxWnZ31F6tY-A_gGuVDBpi33nfwUThUBZfITQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);